(ns xia.task-policy
  "Compatibility facade for policy helpers.

   New code should prefer xia.policy. This namespace preserves the existing
   call-site API while policy logic is split across xia.policy.* domains."
  (:require [xia.policy :as policy]))

(def supervisor-max-identical-iterations policy/supervisor-max-identical-iterations)
(def supervisor-semantic-loop-threshold policy/supervisor-semantic-loop-threshold)
(def supervisor-max-restarts policy/supervisor-max-restarts)
(def supervisor-restart-backoff-ms policy/supervisor-restart-backoff-ms)
(def supervisor-restart-grace-ms policy/supervisor-restart-grace-ms)
(def task-restart-loop-limit policy/task-restart-loop-limit)
(def task-restart-loop-window-ms policy/task-restart-loop-window-ms)
(def autonomous-max-iterations policy/autonomous-max-iterations)
(def autonomous-max-stack-depth policy/autonomous-max-stack-depth)
(def max-tool-rounds policy/max-tool-rounds)
(def max-tool-calls-per-round policy/max-tool-calls-per-round)
(def parallel-tool-timeout-ms policy/parallel-tool-timeout-ms)
(def branch-task-timeout-ms policy/branch-task-timeout-ms)
(def supervisor-phase-timeout-ms policy/supervisor-phase-timeout-ms)
(def supervisor-llm-timeout-ms policy/supervisor-llm-timeout-ms)
(def supervisor-tool-timeout-ms policy/supervisor-tool-timeout-ms)
(def supervisor-worker-timeout-ms policy/supervisor-worker-timeout-ms)
(def max-user-message-chars policy/max-user-message-chars)
(def max-user-message-tokens policy/max-user-message-tokens)
(def max-branch-tasks policy/max-branch-tasks)
(def max-parallel-branches policy/max-parallel-branches)
(def max-branch-tool-rounds policy/max-branch-tool-rounds)
(def branch-error-stack-frames policy/branch-error-stack-frames)
(def llm-status-preview-chars policy/llm-status-preview-chars)
(def llm-status-update-interval-ms policy/llm-status-update-interval-ms)
(def supervisor-tick-ms policy/supervisor-tick-ms)
(def task-control-wait-ms policy/task-control-wait-ms)
(def tool-call-limit-decision policy/tool-call-limit-decision)
(def autonomy-iteration-limit-policy policy/autonomy-iteration-limit-policy)
(def tool-round-limit-decision policy/tool-round-limit-decision)
(def user-message-size-decision policy/user-message-size-decision)
(def branch-task-count-policy policy/branch-task-count-policy)
(def parallel-tool-timeout-policy policy/parallel-tool-timeout-policy)
(def branch-task-timeout-policy policy/branch-task-timeout-policy)
(def restart-policy-decision policy/restart-policy-decision)

(def async-background-max-threads policy/async-background-max-threads)
(def async-background-queue-capacity policy/async-background-queue-capacity)
(def async-parallel-max-threads policy/async-parallel-max-threads)
(def async-parallel-queue-capacity policy/async-parallel-queue-capacity)

(def browser-playwright-timeout-ms policy/browser-playwright-timeout-ms)

(def http-request-retry-config policy/http-request-retry-config)
(def http-request-retry-enabled? policy/http-request-retry-enabled?)
(def http-request-backoff-ms policy/http-request-backoff-ms)
(def http-request-retry-decision policy/http-request-retry-decision)

(def llm-max-provider-retry-rounds policy/llm-max-provider-retry-rounds)
(def llm-max-provider-retry-wait-ms policy/llm-max-provider-retry-wait-ms)
(def llm-retry-after-ms policy/llm-retry-after-ms)
(def llm-retryable-error? policy/llm-retryable-error?)
(def llm-retry-sleep-ms policy/llm-retry-sleep-ms)
(def provider-rate-limit-policy policy/provider-rate-limit-policy)

(def local-doc-ocr-timeout-ms policy/local-doc-ocr-timeout-ms)
(def local-doc-ocr-max-tokens policy/local-doc-ocr-max-tokens)

(def plugin-hook-timeout-ms policy/plugin-hook-timeout-ms)
(def plugin-hook-max-code-chars policy/plugin-hook-max-code-chars)
(def plugin-max-hooks policy/plugin-max-hooks)
(def plugin-max-active-workers policy/plugin-max-active-workers)

(def schedule-failure-backoff-minutes policy/schedule-failure-backoff-minutes)
(def schedule-max-failure-backoff-minutes policy/schedule-max-failure-backoff-minutes)
(def schedule-pause-after-repeated-failures policy/schedule-pause-after-repeated-failures)
(def max-schedules policy/max-schedules)
(def min-schedule-interval-minutes policy/min-schedule-interval-minutes)
(def scheduler-max-concurrent-runs policy/scheduler-max-concurrent-runs)
(def schedule-frequency-policy policy/schedule-frequency-policy)
(def schedule-count-policy policy/schedule-count-policy)
(def schedule-failure-backoff-ms policy/schedule-failure-backoff-ms)
(def schedule-failure-policy policy/schedule-failure-policy)

(def service-rate-limit-policy policy/service-rate-limit-policy)

(def tool-sci-eval-timeout-ms policy/tool-sci-eval-timeout-ms)
(def tool-sci-handler-timeout-ms policy/tool-sci-handler-timeout-ms)
(def tool-max-active-sci-workers policy/tool-max-active-sci-workers)
(def tool-pipeline-timeout-ms policy/tool-pipeline-timeout-ms)
(def tool-pipeline-max-calls policy/tool-pipeline-max-calls)
(def tool-pipeline-max-code-chars policy/tool-pipeline-max-code-chars)
(def normalize-approval-policy policy/normalize-approval-policy)
(def matching-privileged-rules policy/matching-privileged-rules)
(def inferred-tool-approval-policy policy/inferred-tool-approval-policy)
(def tool-approval-policy policy/tool-approval-policy)
(def tool-autonomous-scopes policy/tool-autonomous-scopes)
(def autonomous-tool-allowed? policy/autonomous-tool-allowed?)
(def autonomous-tool-block-message policy/autonomous-tool-block-message)
(def branch-worker-tool-allowed? policy/branch-worker-tool-allowed?)
(def tool-restart-risk-policy policy/tool-restart-risk-policy)
(def tool-execution-decision policy/tool-execution-decision)
